clientSecret: some-client-secret
authServerUserInfoEndpoint: https://foo.us.auth0.com/userinfo
apiPrefix: /api
ddbUserAccessPolicyTableName: baz
ddbAccessPolicyTableName: buz
awsRegion: us-east-1
awsProfile: default